import { ReactNode } from "react";



export interface Job {
  description?: ReactNode;
  title ?: ReactNode;
  id: number;
  company: string;
  logo: string;
  position: string;
  role: string;
  level: string;
  postedAt: string;
  contract: string;
  location: string;
  languages: string[];
  tools: string[];
  email: string;
  phone: string;
  address: string;

}

const localjobs: Job[] = [
    {
      id: 1,
      company: "Photosnap",
      logo: "images/photosnap.svg",
      position: "Senior Frontend Developer",
      role: "Frontend",
      level: "Senior",
      postedAt: "1d ago",
      contract: "Full Time",
      location: "USA Only",
      languages: ["HTML", "CSS", "JavaScript"],
      tools: ['React'],
      description: "Som Senior Frontend Developer på Photosnap kommer du att leda utvecklingen av användargränssnittet för vår plattform. Du kommer att arbeta nära vårt designteam för att implementera användarvänliga och estetiskt tilltalande funktioner. Ditt ansvar kommer att inkludera att optimera prestanda och säkerställa en sömlös användarupplevelse",
      email: "contact@example.com",
      phone: "+1234567890",
      address: "123 Main St, Anytown, Stockholm",
    },
    {
      id: 2,
      company: "Manage",
      logo: "images/manage.svg",
      position: "Fullstack Developer",
      role: "Fullstack",
      level: "Midweight",
      postedAt: "1d ago",
      contract: "Part Time",
      location: "Remote",
      languages: ["Python"],
      tools: ["React"],
      description: "Som Fullstack Developer på Manage kommer du att vara ansvarig för att utveckla och underhålla både frontend- och backend-komponenter av våra applikationer. Du kommer att arbeta i ett distribuerat team och ta ansvar för hela utvecklingscykeln från koncept till distribution.",
      email: "contact@example.com",
      phone: "+1234567890",
      address: "123 Main St, Nya tanneförsväggen, Linköping",
    },
    {
      id: 3,
      company: "Account",
      logo: "images/account.svg",
      position: "Junior Frontend Developer",
      role: "Frontend",
      level: "Junior",
      postedAt: "2d ago",
      contract: "Part Time",
      location: "USA Only",
      languages: ["JavaScript"],
      tools: ["React", "Sass"],
      description: "Som Junior Frontend Developer på Account kommer du att arbeta med att implementera användargränssnitt och användarupplevelser enligt vår designspecifikation. Du kommer att ha möjlighet att lära och växa som utvecklare med stöd från vårt erfarna team.",
      email: "contact@example.com",
      phone: "+1234567890",
      address: "123 Main St, Norrköping, Sweden",
    },
    {
      id: 4,
      company: "MyHome",
      logo: "images/myhome.svg",
      position: "Junior Frontend Developer",
      role: "Frontend",
      level: "Junior",
      postedAt: "5d ago",
      contract: "Contract",
      location: "USA Only",
      languages: ["CSS", "JavaScript"],
      tools: ['React, sass'],
      description: "Som Junior Frontend Developer på MyHome kommer du att arbeta med att utveckla och förbättra användargränssnittet för vår plattform. Du kommer att ha möjlighet att arbeta med moderna frontend-teknologier och bidra till att skapa en innovativ produkt.",
      email: "contact@example.com",
      phone: "+1234567890",
      address: "123 Main St, Anytown, USA",
    },
    {
      id: 5,
      company: "Loop Studios",
      logo: "images/loop-studios.svg",
      position: "Software Engineer",
      role: "Fullstack",
      level: "Midweight",
      postedAt: "1w ago",
      contract: "Full Time",
      location: "Worldwide",
      languages: ["JavaScript", "Ruby"],
      tools: ["Sass"],
      description: "Som Software Engineer på Loop Studios kommer du att arbeta med att utveckla och underhålla våra applikationer och system. Du kommer att vara involverad i hela utvecklingsprocessen och ha möjlighet att påverka produktens arkitektur och design.",
      email: "contact@example.com",
      phone: "+1234567890",
      address: "123 Main St, Anytown, USA",
    },
    {
      id: 6,
      company: "FaceIt",
      logo: "images/faceit.svg",
      position: "Junior Backend Developer",
      role: "Backend",
      level: "Junior",
      postedAt: "2w ago",
      contract: "Full Time",
      location: "UK Only",
      languages: ["Ruby"],
      tools: ["RoR"],
      description: "Som Junior Backend Developer på FaceIt kommer du att arbeta med att utveckla och underhålla våra backend-tjänster och API:er. Du kommer att ha möjlighet att arbeta med moderna teknologier och bidra till att skapa en skalbar och robust infrastruktur.",
      email: "contact@example.com",
      phone: "+1234567890",
      address: "123 Main St, Anytown, USA",
    },
    {
      id: 7,
      company: "Shortly",
      logo: "images/shortly.svg",
      position: "Junior Developer",
      role: "Frontend",
      level: "Junior",
      postedAt: "2w ago",
      contract: "Full Time",
      location: "Worldwide",
      languages: ["HTML", "JavaScript"],
      tools: ["Sass"],
      description: "Som Junior Developer på Shortly kommer du att arbeta med att implementera frontend-funktioner och användarupplevelser för vår plattform. Du kommer att ha möjlighet att lära och växa som utvecklare i ett stöttande team.",
      email: "contact@example.com",
      phone: "+1234567890",
      address: "123 Main St, Anytown, USA",
    },
    {
      id: 8,
      company: "Insure",
      logo: "images/insure.svg",
      position: "Junior Frontend Developer",
      role: "Frontend",
      level: "Junior",
      postedAt: "2w ago",
      contract: "Full Time",
      location: "USA Only",
      languages: ["JavaScript"],
      tools: ["Vue", "Sass"],
      description: "Som Junior Frontend Developer på Insure kommer du att arbeta med att utveckla och förbättra användargränssnittet för våra försäkringsprodukter. Du kommer att ha möjlighet att arbeta med moderna frontend-teknologier och bidra till att skapa en intuitiv användarupplevelse",
      email: "contact@example.com",
      phone: "+1234567890",
      address: "123 Main St, Anytown, USA",
    },
    {
      id: 9,
      company: "Eyecam Co.",
      logo: "images/eyecam-co.svg",
      position: "Full Stack Engineer",
      role: "Fullstack",
      level: "Midweight",
      postedAt: "3w ago",
      contract: "Full Time",
      location: "Worldwide",
      languages: ["JavaScript", "Python"],
      tools: ["Django"],
      description: "Som Full Stack Engineer på Eyecam Co. kommer du att arbeta med att utveckla och underhålla både frontend- och backend-komponenter av våra applikationer. Du kommer att ha möjlighet att arbeta med en variation av teknologier och bidra till att skapa innovativa lösningar",
      email: "contact@example.com",
      phone: "+1234567890",
      address: "123 Main St, London, England",
    },
    {
      id: 10,
      company: "The Air Filter Company",
      logo: "images/the-air-filter-company.svg",
      position: "Front-end Dev",
      role: "Frontend",
      level: "Junior",
      postedAt: "1mo ago",
      contract: "Part Time",
      location: "Worldwide",
      languages: ["JavaScript"],
      tools: ["React", "Sass"],
      description: "Som Front-end Dev på The Air Filter Company kommer du att arbeta med att implementera användargränssnitt och användarupplevelser för vår plattform. Du kommer att ha möjlighet att arbeta med moderna frontend-teknologier och bidra till att skapa en engagerande produkt.",
      email: "contact@example.com",
      phone: "+1234567890",
      address: "123 Main St, Stokholm, SWEDEN",
    },
    {
      id: 11,
      company: "Rektra AB",
      logo: "images/white.svg",
      position: "Fullstack-Development",
      role: "Fullstack",
      level: "Junior",
      postedAt: "1week ago",
      contract: "Full Time",
      location: "Göteborg",
      languages: ["JavaScript"],
      tools: ["React", "Sass"],
      description: "As a Fullstack system developer at UMC, you will design, implement, and test solutions; release, deploy and run operations; maintain and optimise new and existing solutions; and, of course, share knowledge and help your teammates",
      email: "contact@example.com",
      phone: "+1234567890",
      address: "123 Main St, Malmö, SWEDEN",
    },
    {
      id: 12,
      company: "HCL Technologies Sweden AB",
      logo: "images/hcl.svg",
      position: "Fullstack-utvecklare",
      role: "Frontend",
      level: "Junior",
      postedAt: "1mo ago",
      contract: "Part Time",
      location: "Worldwide",
      languages: ["JavaScript"],
      tools: ["React", "Sass"],
      description: "As a Fullstack system developer at UMC, you will design, implement, and test solutions; release, deploy and run operations; maintain and optimise new and existing solutions; and, of course, share knowledge and help your teammates",
      email: "contact@example.com",
      phone: "+1234567890",
      address: "123 Main St, Brlin, GERMANY",
    },
    {
      id: 13,
      company: "Unionall AB",
      logo: "images/logoooo.svg",
      position: "Front-end Dev",
      role: "Frontend",
      level: "Junior",
      postedAt: "1mo ago",
      contract: "Part Time",
      location: "Worldwide",
      languages: ["JavaScript"],
      tools: ["React", "Sass"],
      description: "As a Fullstack system developer at UMC, you will design, implement, and test solutions; release, deploy and run operations; maintain and optimise new and existing solutions; and, of course, share knowledge and help your teammates",
      email: "contact@example.com",
      phone: "+1234567890",
      address: "123 Main St, Aten, GRECE",
    },
    {
      id: 14,
      company: "Monitor ERP SystemAB",
      logo: "images/images.png",
      position: "Fullstack-Developer",
      role: "Frontend",
      level: "Junior",
      postedAt: "1mo ago",
      contract: "Part Time",
      location: "Worldwide",
      languages: ["JavaScript"],
      tools: ["React", "Sass"],
      description: "As a Fullstack system developer at UMC, you will design, implement, and test solutions; release, deploy and run operations; maintain and optimise new and existing solutions; and, of course, share knowledge and help your teammates",
      email: "contact@example.com",
      phone: "+1234567890",
      address: "123 Main St, Anytown, SWEDEN",
    },
    {
      id: 15,
      company: "Lendo - Stockholm",
      logo: "images/lendo.jpeg",
      position: "Front-end Dev",
      role: "Frontend",
      level: "Junior",
      postedAt: "1mo ago",
      contract: "Part Time",
      location: "Worldwide",
      languages: ["JavaScript"],
      tools: ["React", "Sass"],
      description: "As a Fullstack system developer at UMC, you will design, implement, and test solutions; release, deploy and run operations; maintain and optimise new and existing solutions; and, of course, share knowledge and help your teammates",
      email: "contact@example.com",
      phone: "+1234567890",
      address: "123 Main St, Anytown, SWEDEN",
    },
    {
      id: 16,
      company: "Euro Accident Livförsäkring AB",
      logo: "images/EURO.png",
      position: "Systemutvecklare",
      role: "Frontend",
      level: "Junior",
      postedAt: "1mo ago",
      contract: "Part Time",
      location: "Worldwide",
      languages: ["JavaScript"],
      tools: ["React", "Sass"],
      description: "As a Fullstack system developer at UMC, you will design, implement, and test solutions; release, deploy and run operations; maintain and optimise new and existing solutions; and, of course, share knowledge and help your teammates",
      email: "contact@example.com",
      phone: "+1234567890",
      address: "123 Main St, Anytown, SEWEDEN",
    },
    {
      id: 17,
      company: "CELEMI Celemiab international AB",
      logo: "images/CELEMI.jpeg",
      position: "Mjukvaruutvecklare",
      role: "Frontend",
      level: "Junior",
      postedAt: "1mo ago",
      contract: "Part Time",
      location: "Worldwide",
      languages: ["JavaScript"],
      tools: ["React", "Sass"],
      description: "As a Fullstack system developer at UMC, you will design, implement, and test solutions; release, deploy and run operations; maintain and optimise new and existing solutions; and, of course, share knowledge and help your teammates",
      email: "contact@example.com",
      phone: "+1234567890",
      address: "123 Main St, Anytown, SEWEDEN",
    },
    {
      id: 18,
      company: "Curamet AB",
      logo: "images/curamet.jpeg",
      position: "Fullstack-Developer",
      role: "Frontend",
      level: "Junior",
      postedAt: "1mo ago",
      contract: "Part Time",
      location: "Worldwide",
      languages: ["JavaScript"],
      tools: ["React", "Sass"],
      description: "As a Fullstack system developer at UMC, you will design, implement, and test solutions; release, deploy and run operations; maintain and optimise new and existing solutions; and, of course, share knowledge and help your teammates",
      email: "contact@example.com",
      phone: "+1234567890",
      address: "123 Main St, Anytown, SEWEDEN",
    },
    {
      id: 19,
      company: "Resurs Bank",
      logo: "images/Resurs.webp",
      position: "Front-end Dev",
      role: "Frontend",
      level: "Junior",
      postedAt: "1mo ago",
      contract: "Part Time",
      location: "Worldwide",
      languages: ["JavaScript"],
      tools: ["React", "Sass"],
      description: "As a Fullstack system developer at UMC, you will design, implement, and test solutions; release, deploy and run operations; maintain and optimise new and existing solutions; and, of course, share knowledge and help your teammates",
      email: "contact@example.com",
      phone: "+1234567890",
      address: "123 Main St, Anytown, SEWEDEN",
    },
    {
      id: 20,
      company: "Alten Sverige AB",
      logo: "images/ALTEN.svg",
      position: "Front-end Dev",
      role: "Frontend",
      level: "Junior",
      postedAt: "1mo ago",
      contract: "Part Time",
      location: "Worldwide",
      languages: ["JavaScript"],
      tools: ["React", "Sass"],
      description: "As a Fullstack system developer at UMC, you will design, implement, and test solutions; release, deploy and run operations; maintain and optimise new and existing solutions; and, of course, share knowledge and help your teammates",
      email: "contact@example.com",
      phone: "+1234567890",
      address: "123 Main St, Anytown, SEWEDEN",
    },
    {
      id: 21,
      company: "Nordent",
      logo: "images/nordnet.png",
      position: "Backend-utvecklare",
      role: "Bakend",
      level: "Junior",
      postedAt: "1mo ago",
      contract: "Part Time",
      location: "Worldwide",
      languages: ["JavaScript"],
      tools: ["React", "Sass"],
      description: "As a Fullstack system developer at UMC, you will design, implement, and test solutions; release, deploy and run operations; maintain and optimise new and existing solutions; and, of course, share knowledge and help your teammates",
      email: "contact@example.com",
      phone: "+1234567890",
      address: "123 Main St, Anytown, SEWEDEN",
    },
   
  ];
  
  export default localjobs;




  
  


  